name: Deploy to production EC2 main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1
        with:
          host: 54.252.130.200
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
              cd /home/ubuntu/cdtest
              git pull origin main
              source ~/.nvm/nvm.sh
              nvm use node
              npm install -g pnpm
              pnpm install
              pnpm run build
              pm2 restart all